language: node_js
node_js:
  - 7
  - 10
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_script:
  - sleep 15
script:
  - npm run lint
  - npm run depcheck
  - npm run test
after_success:
  - npm run coveralls
